### ISSUE TITLE
How to get the word "Menu" before the bars

### ISSUE THREAD

**Issue by VerdiH** [andyhqtran/Divi-100-Hamburger-Menu#5]
### NOT an issue, just a question.

Several (older) users of https://www.symbisionacademy.eu/ reported that they could not find the menu. To make it easier for them I would need to add the actual word "Menu" before the hamburger bars.

I've tried several things but can't figure it out. Please help.

**Comment by erikgeurts** [comment]
I searched on Google for "divi hamburger menu word menu" and found this: https://divibooster.com/adding-text-before-the-divi-menu-button/

**Comment by VerdiH** [comment]
Hi Erik,

I actually tried that one already. I Also have the Divi Booster plugin. Sadly that solution only works on the mobile menu (as is activated on my site).

I'm using Divi's slide-in menu and your Divi 100 hamburger menu. Of only that one had an option to add text.

Any other suggestion you might have is most welcome!

**Comment by erikgeurts** [comment]
I'm not the developer, just an ordinary user.

**Comment by VerdiH** [comment]
Ah, sorry. I'll just wait for the Dev. Thanks for trying to help though!

**Comment by SJ-James** [comment]
Ver3 if you share your site url I can give you the code.

**Comment by VerdiH** [comment]
Thank you in advance SJ, I still can't get it right: https://www.symbisionacademy.eu/

To get that, I used this code. But no amount of pading or margin can get it aligned. I hope you code will allow me to horizontally align with the bars (beter yet, have it in that container so it shares the same background)

The code I mentioned:

#et-top-navigation:before{
content:"Menu";
font-size:20px;
color: #1E73BE;
}

**Comment by SJ-James** [comment]
Here you go @Ver3. 

#main-header .et_pb_header_toggle.et_toggle_slide_menu {
    padding-left: 80px !important;
    width: 120px !important;
}

#main-header .et_pb_header_toggle.et_toggle_slide_menu:before {
    position: absolute;
    display: block;
    font-family: 'Open Sans' !important;
    content: "MENU";
    color: #f38630;
    font-size: 22px;
    top: 30px;
    left: 10px;
}

/* WHEN MENU IS OPEN */

#main-header .et_pb_header_toggle.et_toggle_slide_menu.et_divi_100_custom_hamburger_menu__icon--toggled:before {
    opacity: 1;
    content: "CLOSE";
    color: #dd3333;
}

You'll have to remove the one you had started already.

**Comment by VerdiH** [comment]
Thank you for responding so quickly @SJ-James and for helping out!

With just a minor change it's now exactly as we needed. Many thanks!!

Ps. I bought Divi Switch, love your work.

**Comment by SJ-James** [comment]
Thanks man :) Happy to help.
